version: '2'
services:
    emrexdemo-app:
        image: emrexdemo
        external_links:
            - emrexdemo-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/emrexdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    emrexdemo-mysql:
        extends:
            file: mysql.yml
            service: emrexdemo-mysql
